baseURL = "https://rc-web-crawler.github.io/"
languageCode = 'en-us'
title = 'Web Crawler'
theme="hyde"

[Menus]
  main = [
      {Name = "Source Code", URL = "https://github.com/RC-Web-crawler/Hugo-site"}
  ]

[params]
  description = """
  A webpage for our Web-Crawler study group. :)
  """
  themeColor = "theme-base-08"